sonar.projectKey=project1
sonar.projectName=Project 1 - Python Web App
sonar.sources=backend/app
sonar.tests=backend/tests
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12
