spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
  cache:
    type: none
  data:
    redis:
      host: localhost
      port: 6379

management:
  metrics:
    export:
      cloudwatch:
        enabled: false
