version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 10
    groups:
      aws-actions:
        patterns:
          - "aws-actions/*"
      github-actions:
        patterns:
          - "actions/*"

  - package-ecosystem: "terraform"
    directory: "/infrastructure/environments/dev"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "terraform"

  - package-ecosystem: "terraform"
    directory: "/infrastructure/environments/prod"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "terraform"
