replicaCount: 2

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
  hosts:
    - host: orders.example.com
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 256m
    memory: 512Mi
  limits:
    cpu: 512m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

env:
  AWS__Region: us-east-1
  AWS__OrdersTable: orders
  AWS__InventoryQueueUrl: ""

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: ""
